
export const supabaseUrl = "https://ahztltkxqakjxbrejcsy.supabase.co"
export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoenRsdGt4cWFranhicmVqY3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAwOTMxNzksImV4cCI6MjA0NTY2OTE3OX0.ZqBywlzBBDZhmtfbe6KNnndtqsMk-aDatV7ofQYZrY4"
